apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-{{ .Values.app.name }}-cluster-role
rules:
  - apiGroups:
      - io.github.onecx.product.store
    resources:
      - products
      - products/status
      - products/finalizers
    verbs:
      - get
      - list
      - watch
      - patch
      - update
      - create
      - delete